#!/usr/bin/env python
import argparse

from board import Board
from game import Game
import tui
import gui

def main():

    parser = argparse.ArgumentParser(description='Pysweeper game.')
    parser.add_argument('--tui', default=False, action='store_true',
                        help='Starts the game in text mode')
    args = parser.parse_args()

    board = Board(10, 10)
    board.generate(20)

    game = Game(board)

    if args.tui:
        ui = tui.UserInterface(game)
    else:
        ui = gui.UserInterface(game)

    ui.main_loop()

if __name__ == '__main__':
    main()

